### ISSUE TITLE
mon command not found

### ISSUE THREAD

**Issue by LikoV2** [ITRS-Group/monitor-merlin#30]
Hi,

I'm trying to update my naemon configuration to Ninja, and try to make a cluster with Merlin. However, although the installation of Merlin went OK (no error), I don't have the "mon" command. I can't find it.

Can I ask which environment you are working on ? I'm trying on CentOS 7, as I can find all the requirements, unlike with Debian 9.

**Comment by jacobbaungard** [comment]
Hi,

We use CentOS.

The mon command is located in the apps directory, and I guess there are no install scripts, other than the spec file, that ensures they are installed. When built there is a apps/op5 executable, which is the same as the mon command. Checkout the code in the spec file: https://github.com/op5/merlin/blob/efedb2be49225d9802de2d1739534da1f49301c0/merlin.spec#L137

**Comment by jacobbaungard** [comment]
`/opt/monitor/etc/mconf` is the default merlin module configuration path for OP5 monitor, which is why it is configured like that. I assume the default is `/etc/naemon` which is perfectly fine.

Buildroot is defined here which is just the current folder were the source is being built:
https://github.com/op5/merlin/blob/efedb2be49225d9802de2d1739534da1f49301c0/merlin.spec#L33

Actually I took a look and I think the makefile actually does install the scripts local in apps. Do you have the op5 script in your install path? If you do I think it would be enough to locate that (`which op5`) and then make create a symlink from op5->mon in that same folder.

**Comment by jacobbaungard** [comment]
Did you manage to get this to work?

**Comment by jacobbaungard** [comment]
Hi,

I will close this old issue, assuming it is no longer relevant. These days we build RPM packages for easier installation including the `mon` command. Instructions can be found here: https://itrs-group.github.io/monitor-merlin/

Feel free to open a new issue if you are still having issues.
