### ISSUE TITLE
track_current deprecated

### ISSUE THREAD

**Issue by Patriarcha** [ITRS-Group/monitor-merlin#47]
Hi
I set track current on yes, I can see warning about this option beeing deprecated, it is no writing to database about host etc. 
Is this expected?
Shouldn't that write to database although warning?

If this is as expected, what is alternative to write that informations to database?

**Comment by jacobbaungard** [comment]
Hi,

Yes this is expected behavior - the functionality was removed a long time ago (due to scalability issues with this approach iirc). The configuration options exists just in case someone still had the setting in their config file after upgrading.

It is recommended to not use a database for this kind of information and use something like livestatus+lmd instead to fetch current status information.
